project:
  type: default
  output-dir: docs
  render:
    - informe.qmd

format:
  html:
    css: informe.css
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: false
    code-tools: true
    code-overflow: wrap
    theme: cosmo

execute:
  echo: true
  warning: false
  freeze: false
